name: hte
version: 0.0.1.0
github: "SeedyROM/hte"
license: BSD3
author: "Zack Kollar"
maintainer: "me@seedyrom.io"
copyright: "2020 Zack Kollar"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/hte#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - cmdargs
  - Cabal
  - terminal

library:
  source-dirs: src

executables:
  hte:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hte

tests:
  hte-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hte
